#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT_5x6(
            LT(4,KC_ESC), KC_1, KC_2, KC_3, KC_4, KC_5,       KC_6, KC_7, KC_8, KC_9, KC_0, LT(4,KC_MINS),
            KC_TAB, KC_Q, KC_D, KC_R, KC_W, KC_B,             KC_J, KC_F, KC_U, KC_P, KC_SCLN, KC_BSLS,
            KC_LCTL, KC_A, KC_S, KC_H, KC_T, KC_G,            KC_Y, KC_N, KC_E, KC_O, KC_I, KC_QUOT, KC_LSFT,
            KC_Z, KC_X, KC_M, KC_C, KC_V,                     KC_K, KC_L, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
            KC_LEFT, KC_RGHT,                                 KC_UP, KC_DOWN,
            LT(2,KC_BSPC), LT(1,KC_DEL),                      LT(2,KC_ENT), LT(1,KC_SPC),
            // Bottom left thumb
            LT(2,KC_HOME),
                          KC_LALT,                            KC_RALT, KC_RCTL,
            // Bottom left thumb rightmost
            LT(3,KC_END),
            KC_LGUI,                                          LT(3,KC_GRV), KC_COPY),

	[1] = LAYOUT_5x6(KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, KC_EQL, KC_MINS, KC_TRNS, KC_LPRN, KC_RPRN, KC_LPRN, KC_RPRN, KC_P7, KC_P8, KC_P9, KC_MINS, KC_PPLS, LCTL_T(KC_BSLS), KC_EQL, KC_GRV, KC_LCBR, KC_RCBR, LSFT(KC_LBRC), RSFT(KC_RBRC), KC_P4, KC_P5, KC_P6, KC_EQL, RCTL_T(KC_BSLS), KC_LSFT, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_LBRC, KC_RBRC, KC_P1, KC_P2, KC_P3, KC_TRNS, KC_UNDS, KC_TRNS, KC_PSCR, KC_TRNS, KC_P0, KC_BSPC, KC_TRNS, KC_EQL, KC_P0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSTE),
	[2] = LAYOUT_5x6(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_NO, LALT_T(KC_F7), KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_RBRC, KC_TRNS, KC_NLCK, KC_INS, KC_SLCK, KC_MUTE, C_S_T(KC_GRV), KC_UP, KC_DOWN, KC_LEFT, KC_RGHT, KC_TRNS, RSFT(KC_RBRC), KC_MPRV, KC_MPLY, KC_MNXT, KC_TRNS, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LPRN, KC_RPRN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_EQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCTL, KC_LCTL, KC_RCTL, KC_RCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_5x6(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN2, KC_MS_U, KC_BTN1, KC_WH_U, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL1, KC_ACL2, KC_MS_L, KC_MS_R, KC_ACL0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS),
	[4] = LAYOUT_5x6(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, EEP_RST, EEP_RST, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RESET, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS)
};
